### PR TITLE
Implement RayleighRV

### PR DESCRIPTION
**Pull request by twiecki**
### Motivation for these changes
Implement RayleighRV, downstream of https://github.com/aesara-devs/aesara/pull/1433

### Implementation details
...

### Checklist
+ [ ] Explain motivation and implementation 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- Implement RayleighRV. Downstream of Aesara PR #1433 https://github.com/aesara-devs/aesara/pull/1433

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

### CODE REVIEW

**Comment by ricardoV94** [comment]
Why isn't it picking the more informative titles: https://github.com/pymc-devs/pytensor/blob/4730d0cb7db40bd25d937bcbcf187b8bdec4e6de/bin/downstream_pr.sh#L46

**Comment by twiecki** [comment]
Because there were conflicts and I finished it manually.

**Comment by ricardoV94** [comment]
Can you edit it? It's not useful for the release notes like this

**Comment by ricardoV94** [comment]
I am not sure we should implement it as a new Op. According to the web rayleigh is just a scaled chi2 with 2 df, so this should be the same:

```python
def rayleigh(scale, *, size=None, rng=None, dtype=None):
  return chi2(df=2, rng=rng size=size, rngdtype=dtype) * as_tensor_variable(scale)
```

https://github.com/scipy/scipy/blob/dde50595862a4f9cede24b5d1c86935c30f1f88a/scipy/stats/_continuous_distns.py#L7669-L7787

The advantage being we don't need to implement new JAX or Numba Ops, nor implement logp in PyMC

**Pull request closed without merging**
