### PR TITLE
Remove more unused config options

### PR DESCRIPTION
**Pull request by Armavica**
## Description

Note that I changed the value of `in_c_key` for `cast_policy` because I assumed that it was meant to be `False`, but I could be wrong.

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Why didn't tests run?

**Comment by maresb** [comment]
> Why didn't tests run?

What do you mean?

image

**Comment by ricardoV94** [comment]
Ugh, in the android app I see this: []()

**Comment by maresb** [comment]
Ok, so it was just a glitch? (GitHub seems really flaky about this stuff in general.)

**Comment by Armavica** [comment]
You might be seeing an earlier workflow, not the final one

**Pull request merged**
