### PR TITLE
Add jax implementation of `pt.linalg.pinv`

### PR DESCRIPTION
**Pull request by jessegrabowski**
### Motivation for these changes
Add a jax implementation of `pt.linalg.pinv`

### Implementation details
Not the most elaborate PR:

```
@jax_funcify.register(MatrixPinv)
def jax_funcify_Pinv(op, **kwargs):
    def pinv(x):
        return jnp.linalg.pinv(x)

    return pinv
```

### Checklist
+ [ x] Explain motivation and implementation 👆
+ [ x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [x ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
None

## New features
You can compile graphs with `pinv` to JAX

## Bugfixes
None

## Documentation
None

## Maintenance
None

### CODE REVIEW

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks @jessegrabowski

**Comment by ricardoV94** [comment]
Oops missed one float32 test was failing: https://github.com/pymc-devs/pytensor/actions/runs/4968627533/jobs/8891362025?pr=294

**Comment by jessegrabowski** [comment]
I didn't add `as_dtype(config.floatX)` to the test array (again...). Not sure how to proceed -- I deleted the branch on my fork already so it's not auto-pushing the change into this PR.

**Comment by ricardoV94** [comment]
No worries, I opened a fix PR in #296

**Pull request merged**
