### PR TITLE
Update aliases to reflect package name

### LINKED ISSUE #275: Missing conv documentation
### Issue with current documentation:

I was looking for convolutional operator, but the [PyTensor's document](https://pytensor.readthedocs.io/en/latest/library/tensor/conv.html) seems to be missing

### Idea or request for content:

Add how to use `conv` operator in the document

### PR DESCRIPTION
**Pull request by jessegrabowski**
## Description

This PR changes all the aliases in all the code from `at`, `aes`, `aer`, etc., to `pt`, `ps`, `ptr`, etc. This includes in tests, docs, and the main codebase.

Also I directly changed the .rst files in the docs, I'm not sure if I was supposed to do that, or if those are auto-generated?

## Related Issue

- [x] Closes issue: #380 
- [] Related issue (not closed by this PR):

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by ricardoV94** [comment]
There's much more `import pytensor.tensor as at` in the codebase. Do you want to fix it or remove the one file you changed? Otherwise it's a bit odd (but not a big deal). That touches on https://github.com/pymc-devs/pytensor/issues/380

**Comment by jessegrabowski** [comment]
I'll just do it all what the heck.

**Review by twiecki — APPROVED** [review]

**Comment by jessegrabowski** [comment]
@ricardoV94  I think I got everything

**Comment by ricardoV94** [comment]
> @ricardoV94  I think I got everything

I'll take your word for it. If this was your long con to mine bitcoin from pymc users hats-off to you in advance

**Pull request merged**
