### PR TITLE
Revert "Run numba tests in python 3.10 instead of 3.11"

### LINKED ISSUE #239: Test Numba with Python 3.11 once it is supported
### Description

Once Numba is released for Python 3.11, we should test it, and revert 277559b411886c3dc1161cf197c5f250048ecec5

https://github.com/numba/numba/issues/8304

### PR DESCRIPTION
**Pull request by ricardoV94**
This reverts commit 277559b411886c3dc1161cf197c5f250048ecec5 and  tests numba compatibility with py311

Closes #239

### CODE REVIEW

**Comment by ricardoV94** [comment]
One test with a Categorical seems to fail. I think this was already fixed or marked as ignored upstream in Aesara.

Some tests are xpassing where we can remove the mark.

**Comment by ricardoV94** [comment]
Should we add the new numba version as a lower dependency? 

This PR is not yet using any new functionality from the latest version. Simply marked some tests as xfail and fixed a bug with Categorical that should become irrelevant after #316

**Comment by michaelosthege** [comment]
> Should we add the new numba version as a lower dependency?

For the package or for the test environment?

I would not add it for the package, but for the test environment it might be a good idea

**Comment by ricardoV94** [comment]
Tests are passing can I get a thumbs up @michaelosthege / @maresb ?

**Comment by maresb** [comment]
It looks to me like there are currently no tests running without Numba. If this is the case and I'm not just missing something, maybe it'd make sense to add Numba as a dependency in `pyproject.toml`?

**Review by maresb — APPROVED** [review]
Up to that question about adding Numba as a dep, LGTM.

**Comment by ricardoV94** [comment]
> It looks to me like there are currently no tests running without Numba.

What do you mean? Most tests don't run with numba at all.
Numba is a developer dependency and installed manually in the CI.
Numba is an optional dependency in pyproject.toml as well, just not pinning the latest version, as no feature directly depends on it:
https://github.com/pymc-devs/pytensor/blob/f0fda414c9d49a7337cbb2101583a6969d15a99e/pyproject.toml#L102-L105

**Comment by ricardoV94** [comment]
Merging this to unblock other PRs, but let me know if you think we should bump numba min version in the toml as well

**Comment by maresb** [comment]
Ah, what I said was a bit ambiguous. I meant about Numba being always installed in all the environments in which pytest is run for the CI testing workflow. Specifically, can you point to any particular pytest run in the test workflow which executes in an environment where numba is *not* installed?

**Comment by ricardoV94** [comment]
> Ah, what I said was a bit ambiguous. I meant about Numba being always installed in all the environments in which pytest is run for the CI testing workflow. Specifically, can you point to any particular pytest run in the test workflow which executes in an environment where numba is _not_ installed?

Ah, no that doesn't currently happen the way we split the CIs, but we could easily have the numba ones run on their own job. It used to be distinict before

**Comment by maresb** [comment]
Ok, we might want to split the CIs if we want tests to cover the case of accidentally triggering Numba when it's not supposed to be used. Would this be useful?

**Comment by maresb** [comment]
Exactly.

**Pull request merged**
