### PR TITLE
Fix release pipeline

### PR DESCRIPTION
**Pull request by cerrussell**
#173 

### Motivation for these changes
To support release to PyPi.

### Implementation details
-Configured to generate sdist and CPython based 32 and 64-bit wheels for windows-2022, macos12, and linux
-Command to check for versions of pytensor and scan_perform function included but configured to skip for cp37, musllinux, and 32-bit builds. I also included commented out code to instead not build these if that is desired.
-The version tag may need some work - test runs returned versions like 'pytensor-0+untagged.30079.g7788241', but I'm not clear if this is due to being on a fork and not having the full refs. I will address if needed.
-Release to PyPi section is disabled for now
-I did not integrate the test suite as it requires complex config of the runner, but can work on this if it is desired

### Checklist
+ [x] Explain motivation and implementation 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- Generating wheels for windows, mac, linux for PyPi

## Bugfixes
- ...

## Documentation
- [cibuildwheel](https://cibuildwheel.readthedocs.io/)

## Maintenance
- ...

### CODE REVIEW

**Review by twiecki — APPROVED** [review]

**Review by maresb — COMMENTED** [review]
This looks very promising. I have yet to use cibuildwheel myself, but this looks very good.

What's the status of the tests? Are we testing the build wheels for at least some of the platforms?

**Review by maresb — CHANGES_REQUESTED** [review]
The `upload_pypi.needs` must be adjusted since `build` no longer exists. Perhaps `[check_dist]`?

**Comment by maresb** [comment]
> My initial configuration to run the tests had some issues related to the runner either missing dependencies or being unable to find them - for example, being unable to compile jaxlib. I realized execution would require more in-depth review of the requirements for the testing environment.

I'm not finding any runner logs regarding this. Do you have a link? The only failed run I see is from the recent [Updated upload_pypi action](https://github.com/pymc-devs/pytensor/pull/183/commits/39d10f745e2c4191b1723611bcd7410224af0096) commit.

**Comment by michaelosthege** [comment]
> > My initial configuration to run the tests had some issues related to the runner either missing dependencies or being unable to find them - for example, being unable to compile jaxlib. I realized execution would require more in-depth review of the requirements for the testing environment.
> 
> I'm not finding any runner logs regarding this. Do you have a link? The only failed run I see is from the recent [Updated upload_pypi action](https://github.com/pymc-devs/pytensor/pull/183/commits/39d10f745e2c4191b1723611bcd7410224af0096) commit.

https://github.com/cerrussell/pytensor/actions/runs/3850560155/jobs/6560833376

Regardless, I think running the test suite on every Wheel build is a bit too much. It's slow, and we'd just be testing if `cibuildwheel` did its job correctly.

IMO we can (squash) merge this and give another release a try

**Review by maresb — APPROVED** [review]

**Comment by michaelosthege** [comment]
Thanks a lot @cerrussell for helping us out! It's safe to say that we didn't have the expertise to do this without you!

**Comment by cerrussell** [comment]
@michaelosthege Happy to help!

**Pull request merged**
