### PR TITLE
Experimental: PyTorch backend

### PR DESCRIPTION
**Pull request by twiecki**
I copied the JAX linker code and asked GPT to port the code to pytorch. Haven't tried it but maybe it's a good starting point for someone else.

### CODE REVIEW

**Comment by twiecki** [comment]
OK, so I was able to run the test-suite (adapted from JAX) which of course breaks horribly, but it's something we can iterate on.

**Comment by ricardoV94** [comment]
Oh boy 🥲 this will be a fun one

**Comment by junpenglao** [comment]
image

**Comment by juanitorduz** [comment]
what about using something like https://github.com/lucidrains/jax2torch ?

**Comment by ricardoV94** [comment]
> what about using something like https://github.com/lucidrains/jax2torch ? 

The point is to circumvent jax limitations

**Comment by ricardoV94** [comment]
Closing in favor of #764

**Pull request closed without merging**
