### PR TITLE
Fix E721: do not compare types, for exact checks use is / is not

### PR DESCRIPTION
**Pull request by maresb**
## Description

This splits out a controvertial part of #581 code cleanup. See https://github.com/pymc-devs/pytensor/pull/581#discussion_r1448620228. 

This runs a risk of breaking something extremely subtle, so I think we will not want to merge this, but I wanted to at least give this its own PR number for reference.

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [X] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by ricardoV94** [comment]
I think we can go ahead with this one @maresb

**Comment by maresb** [comment]
@ricardoV94, rebase is complete.

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
@maresb were we suppressing this pre-commit rule, should we reactivate it?

**Comment by maresb** [comment]
> @maresb were we suppressing this pre-commit rule, should we reactivate it?

No we weren't, it's just totally broken in Ruff: https://github.com/astral-sh/ruff/issues/6465

But now E721 passes with flake8

**Pull request merged**
