### PR TITLE
Add slowest test issue CI/CD

### PR DESCRIPTION
**Pull request by wd60622**
## Description

Adding a CI/CD to populate #1124

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

----
📚 Documentation preview 📚: https://pytensor--1125.org.readthedocs.build/en/1125/

### CODE REVIEW

**Comment by wd60622** [comment]
A lot more sections than PyMC Marketing... Should I try for some formatting or would shortening the section "summary" still convey the same information?

**Comment by ricardoV94** [comment]
We can omit the following:
* python3.10 runs
* float32 runs (no reason these should be slower than the float64)
* The `benchmark` suite as it doesn't make sense to "speedup" so take that out as well

**Comment by wd60622** [comment]
> We can omit the following:
> 
> * python3.10 runs
> * float32 runs (no reason these should be slower than the float64)
> * The `benchmark` suite as it doesn't make sense to "speedup" so take that out as well

Done. I've updated the issue with that filter. See how it looks there

**Comment by wd60622** [comment]
I am looking into adding total time next to each section. I think that would be helpful for summary

**Review by ricardoV94 — APPROVED** [review]
just to see if I understand, this reads the tones from the GitHub CI looks?

**Comment by wd60622** [comment]
> just to see if I understand, this reads the tones from the GitHub CI looks?

Tones? The issue at the moment will be how it looks every 6 hours

**Comment by ricardoV94** [comment]
> > just to see if I understand, this reads the tones from the GitHub CI looks?
> 
> Tones? The issue at the moment will be how it looks every 6 hours

Times, fat fingers

**Comment by wd60622** [comment]
> reads the times from the GitHub logs. Fat fingers 

Correct from the CI job rather than from pytest runs. So there might be some cushion added to that with job spin up, etc

**Comment by wd60622** [comment]
But gives some ball park estimate of times for each

**Comment by wd60622** [comment]
Any more feedback @ricardoV94 ?

**Comment by ricardoV94** [comment]
Thanks @wd60622

**Comment by ricardoV94** [comment]
My question above wasn' clear. I was confirming this job does not need to run seperate CI tests, but instead simply reads the logs of the existing CI tests

**Pull request merged**
