### PR TITLE
Fix docstrings reference for the betainc_grad function

### PR DESCRIPTION
**Pull request by amyoshino**
### Motivation for these changes
Currently, the [betainc_grad()](https://github.com/pymc-devs/pytensor/blob/0b558d8e65ee6603b80be566d36a036b68a97ee0/pytensor/scalar/math.py#L1363C24-L1363C52) and [gammainc_grad()](https://github.com/pymc-devs/pytensor/blob/0b558d8e65ee6603b80be566d36a036b68a97ee0/pytensor/scalar/math.py#L715C36-L715C36) functions have the same docstring:
```
Gradient of the regularized lower gamma function (P) wrt to the first
argument (k, a.k.a. alpha).

Adapted from STAN `grad_reg_lower_inc_gamma.hpp`

Reference: Gautschi, W. (1979). A computational procedure for incomplete gamma functions.
ACM Transactions on Mathematical Software (TOMS), 5(4), 466-481.
```

The fix attempts to clarify the function and indicates a probable resource that was utilized during the development of the function. I attempted to determine if it was indeed adapted from STAN, like in the case of 'Gradient of the regularized lower gamma function', but I couldn't be entirely certain. In any case, I've opened this PR to initiate a discussion on how to address this. Please let me know if I have referred to the incorrect resource.

### Implementation details
...

### Checklist
+ [ ] Explain motivation and implementation 👆
+ [ ] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [ ] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [ ] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- ...

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

### CODE REVIEW

**Comment by ricardoV94** [comment]
Nice catch. IIRC this is actually not adapted from STAN. I'll try to retrieve the references

**Comment by ricardoV94** [comment]
The docstring was correct prior to the refactor in https://github.com/pymc-devs/pytensor/commit/39d37df624666db2b9cff796cd0560f8b4fd5ca6 so we can recover it from there. Seems to have been:

```python
    """
    Gradient of the regularized incomplete beta function wrt to the first
    argument (alpha) or the second argument (beta), depending on whether the
    fourth argument to betainc_der is `True` or `False`, respectively.

    Reference: Boik, R. J., & Robison-Cox, J. F. (1998). Derivatives of the incomplete beta function.
    Journal of Statistical Software, 3(1), 1-20.
    """
```
We should change the text to something like

```python
    """
    Gradient of the regularized incomplete beta function wrt to the first
    argument `p` (aka alpha) or the second argument `q` (aka beta),
    depending on whether `wrtp` is true.

    Reference: Boik, R. J., & Robison-Cox, J. F. (1998). Derivatives of the incomplete beta function.
    Journal of Statistical Software, 3(1), 1-20.
    """
```

**Comment by amyoshino** [comment]
Thanks for pointing out the references! I updated the code to reflect your suggestions. Let me know if I miss anything.

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Thanks @amyoshino

**Pull request merged**
