### PR TITLE
Fix failing CI in Python 3.8 and install numba/jax on specific runs

### LINKED ISSUE #322: Test Numba/ JAX in separate CI
### Description

Right now NUMBA/JAX is always installed. We should only install them for the respective tests, so that we guarantee PyTensor keeps working without those optional dependencies.

### PR DESCRIPTION
**Pull request by ricardoV94**
Also closes #322 even though the main goal was to fix the failing CI

### CODE REVIEW

**Comment by ricardoV94** [comment]
It seems that in the Python 3.8 CI, the blas is not getting setup correctly? It fails here: 

https://github.com/pymc-devs/pytensor/blob/72231948b7125f9adfec23eb3bcdd297007183ed/.github/workflows/test.yml#L126

**Comment by ricardoV94** [comment]
The difference seems to be that it's installing `numpy` from `pypi`?

https://github.com/pymc-devs/pytensor/actions/runs/5121096515/jobs/9208464120?pr=326#step:5:92
```
Installing collected packages: toolz, numpy, filelock, logical-unification, cons, etuples, miniKanren, pytensor
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.3
    Uninstalling numpy-1.24.3:
      Successfully uninstalled numpy-1.24.3
```

https://github.com/pymc-devs/pytensor/actions/runs/5121096515/jobs/9208464120?pr=326#step:5:197
```
numpy                     1.22.4                   pypi_0    pypi
```

Whereas it did not do this in a previous successful run:
https://github.com/pymc-devs/pytensor/actions/runs/5079024125/jobs/9124296946?pr=280#step:5:190

**Comment by ricardoV94** [comment]
This is my suspect: https://github.com/conda-forge/numba-scipy-feedstock/pull/4/files

**Comment by ricardoV94** [comment]
> This is my suspect: https://github.com/conda-forge/numba-scipy-feedstock/pull/4/files

Yes that's the problem. The new upper pin on `scipy 1.7.3` causes that to be chosen, and I guess it now pins numpy whereas the old `scipy 1.6.2` did not.

**Comment by maresb** [comment]
Nice detective work! Here's the upper pin on numpy:
https://github.com/conda-forge/scipy-feedstock/pull/219

But why would this lead to pip downgrading numpy?

**Comment by ricardoV94** [comment]
> Nice detective work! Here's the upper pin on numpy: [conda-forge/scipy-feedstock#219](https://github.com/conda-forge/scipy-feedstock/pull/219)
> 
> But why would this lead to pip downgrading numpy?

To the best of my understanding when doing `pip install -e .`, pip sees a PyTensor has a dependency on scipy -> figures out numpy is incompatible -> installs new numpy.

I fixed it by forcing the numpy pin when installing numba on the CI. I checked it worked and now pushed a second commit that only installs numba/ jax in their own jobs to address #322

**Comment by ricardoV94** [comment]
> Nice detective work! Here's the upper pin on numpy: [conda-forge/scipy-feedstock#219](https://github.com/conda-forge/scipy-feedstock/pull/219)

Specifically, this backport to 1.7: https://github.com/conda-forge/scipy-feedstock/pull/217

I don't think they ever did it to 1.6, so we were not seeing this problem before

**Comment by maresb** [comment]
> Specifically, this one to the 1.7 branch

Ah, thanks!!! This is the crucial piece I was missing; I was looking at `main`.

**Review by maresb — APPROVED** [review]
A few stylistic wishes, but LGTM

I found 2c91ff724409e1233a2500c35cb3a3d388b7cf4d a little bit confusing because it almost cherrypicks the reverted 277559b411886c3dc1161cf197c5f250048ecec5, but not quite. (It would have been nice to see 2c91ff724409e1233a2500c35cb3a3d388b7cf4d cherry-picked in one commit and then tweaked in the next.)

I wonder if it makes sense to inline the commit message of a1dd6f5a682c29e367bbe5bde1d222ec5fa27d5e because otherwise you have to look in the blame to see the explanation for the numpy upper bound.

**Comment by ricardoV94** [comment]
https://github.com/pymc-devs/pytensor/commit/2c91ff724409e1233a2500c35cb3a3d388b7cf4d looks superficially similar but the goal is something totally different: Run both JAX and NUMBA on their own CIs to address #322 

I'll inline the comment, hopefully yaml doesnt' complain

**Comment by maresb** [comment]
VS Code says invalid as-is, but valid indented.

**Comment by ricardoV94** [comment]
Wanna push? Away from PC now

**Comment by ricardoV94** [comment]
Thanks @maresb

**Pull request merged**
