### PR TITLE
Code cleanups

### PR DESCRIPTION
**Pull request by Armavica**
## Description

* use `Counter` and `defaultdict` where appropriate
* simplify boolean operations
* use list comprehensions where appropriate
* remove custom `OrderedDict` because `dict` is ordered since Python 3.7
* rewrite `OrderedSet` in terms of a `dict`

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by ricardoV94** [comment]
I wouldn't remove kanren if we don't have to. While the library itself (nor PyMC) is using it, it was added as a way to implement more powerful rewrites than what is possible with PyTensor built-in machinery. Since that's one of the strong points of PyTensor vs other tensor libraries, I would like to keep that around unless there's a strong objection?

**Comment by jessegrabowski** [comment]
It's sort of in the same category as egg-log -- something we could use but don't currently.

Maybe we need to discuss how/where/if it can be used in a future design meeting? I've asked @ricardoV94 about it in private a couple times and the response was always "idk, lol"

**Comment by Armavica** [comment]
Sure, no worries. I'll debug what kanren doesn't like with the frozenset commit then.

**Comment by ricardoV94** [comment]
Otherwise I checked the rest of the PR and changes look fine. Had some doubts about replacing frozendict in the elemwise pattern, but I see how the less readable tuple may be still a good trade-off vs the frozen-dict (custom or via a dependency).

**Comment by ricardoV94** [comment]
If you find a bug in kanren, open an issue over there?

**Comment by Armavica** [comment]
@ricardoV94 I ended up reverting the removal of the custom `frozendict` implementation that we have. My analysis could be at least partially wrong, but I think the problem was the following:
* With this change, `Elemwise.inplace_pattern` went from a `frozendict` to an empty tuple
* this was creating a problem with `kanren` which expects some expressions as `ExpressionTuples` (or simple tuples), was assuming that this tuple was one of them, and crashing because it was empty.

Presumably, a fix would be to have `kanren` do a more precise type check `isinstance(..., ExpressionTuple)` instead of `isinstance(..., Sequence)`, but this looks like more work in `kanren` than I have time to do now.

**Comment by ricardoV94** [comment]
What test was failing specifically?

**Comment by Armavica** [comment]
> What test was failing specifically?

`test_KanrenRelationSub_filters`

**Comment by ricardoV94** [comment]
The empty tuple should be something we or kanren can fix. But let's leave that for later. Can you open a draft PR and linked issue with the frozendict removed so it's easier to investigate when we have the time? We can get the rest merged in the meantime

**Review by ricardoV94 — APPROVED** [review]

**Comment by Armavica** [comment]
Sure, I will do that when this one is merged (it's easier on top of this branch).

**Pull request merged**
