### PR TITLE
Slight cleanup of the ruff configuration

### LINKED ISSUE #601: Fix `UP031: Use format specifiers instead of percent format` in code base
### Description

To fix `pyupgrade` in https://github.com/pymc-devs/pytensor/pull/586,  we had to skip` UP031: Use format specifiers instead of percent format` because otherwise, we get `135 errors`. We want to fix these errors and stop ignoring `UP031`.

### PR DESCRIPTION
**Pull request by Armavica**
## Description

I cleaned up some unused lints and tried to fix #601 with ruff's (unsafe) autofix.

## Related Issue

- [x] Closes #601
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Review by maresb — APPROVED** [review]
Nice!!!

We should probably add `RUF100 unused-noqa`. We may also want to see what happens if we select all of `RUF`.

That could be done in a separate PR.

**Review by juanitorduz — APPROVED** [review]
wow! nice

**Comment by Armavica** [comment]
Thank you for the reviews! Is there something to do for the failing Coverage upload?

**Comment by ricardoV94** [comment]
Thanks @Armavica 

My guess is the codecov was just a fluke

**Pull request merged**
