### PR TITLE
Improve Op string representation and debug_print formatting

### LINKED ISSUE #196: Don't repeat inner graphs with multiple outputs in debugprint
### Description

```python
import pytensor
import pytensor.tensor as pt
x = pt.vector("x")
outs, _ = pytensor.scan(
    fn = lambda x: (
        pt.exp(pt.random.normal(x)),
        pt.log(pt.random.normal(x)), 
        pt.cos(pt.random.normal(x)),
    ),
    sequences=[x],
)
fn = pytensor.function([x], outs)
pytensor.dprint(fn)
```
```
for{cpu,scan_fn}.0 [id A] 5
 |Shape_i{0} [id B] 0
 | |x [id C]
 |Subtensor{int64:int64:int8} [id D] 4
 | |x [id C]
 | |ScalarFromTensor [id E] 3
 | | |Elemwise{Composite{Switch(LE(i0, i1), i1, i2)}} [id F] 2
 | |   |Shape_i{0} [id B] 0
 | |   |TensorConstant{0} [id G]
 | |   |TensorConstant{0} [id H]
 | |ScalarFromTensor [id I] 1
 | | |Shape_i{0} [id B] 0
 | |ScalarConstant{1} [id J]
 |Shape_i{0} [id B] 0
 |Shape_i{0} [id B] 0
 |Shape_i{0} [id B] 0
 |RandomGeneratorSharedVariable(<Generator(PCG64) at 0x12E952EA0>) [id K]
 |RandomGeneratorSharedVariable(<Generator(PCG64) at 0x12E89F4C0>) [id L]
 |RandomGeneratorSharedVariable(<Generator(PCG64) at 0x12E8E4740>) [id M]
for{cpu,scan_fn}.1 [id A] 5
for{cpu,scan_fn}.2 [id A] 5

Inner graphs:

for{cpu,scan_fn}.0 [id A]
 >Elemwise{exp,no_inplace} [id N]
 > |normal_rv{0, (0, 0), floatX, False}.1 [id O]
 >   |*1-<RandomGeneratorType> [id P] -> [id K]
 >   |TensorConstant{[]} [id Q]
 >   |TensorConstant{11} [id R]
 >   |*0-<TensorType(float64, ())> [id S] -> [id D]
 >   |TensorConstant{1.0} [id T]
 >Elemwise{log,no_inplace} [id U]
 > |normal_rv{0, (0, 0), floatX, False}.1 [id V]
 >   |*2-<RandomGeneratorType> [id W] -> [id L]
 >   |TensorConstant{[]} [id Q]
 >   |TensorConstant{11} [id R]
 >   |*0-<TensorType(float64, ())> [id S] -> [id D]
 >   |TensorConstant{1.0} [id T]
 >Elemwise{cos,no_inplace} [id X]
 > |normal_rv{0, (0, 0), floatX, False}.1 [id Y]
 >   |*3-<RandomGeneratorType> [id Z] -> [id M]
 >   |TensorConstant{[]} [id Q]
 >   |TensorConstant{11} [id R]
 >   |*0-<TensorType(float64, ())> [id S] -> [id D]
 >   |TensorConstant{1.0} [id T]

for{cpu,scan_fn}.1 [id A]
 >Elemwise{exp,no_inplace} [id N]
 >Elemwise{log,no_inplace} [id U]
 >Elemwise{cos,no_inplace} [id X]

for{cpu,scan_fn}.2 [id A]
 >Elemwise{exp,no_inplace} [id N]
 >Elemwise{log,no_inplace} [id U]
 >Elemwise{cos,no_inplace} [id X]
```

The last two entries of inner-graphs are completely redundant, since the information is already contained in the first inner graph. This will be even more relevant after #121 as multiple output Composites will also be printed like this.

Does anyone know a good reason for repeating the outputs in inner graphs? Maybe inplace or view info?

### LINKED ISSUE #313: Make debug_print more readable
### Description

```
import pytensor
import pytensor.tensor as pt

x = pt.scalar("x")
y = pt.vector("y")
z = x + pt.exp(y)

pytensor.dprint(z)
```
```
Elemwise{add,no_inplace} [id A]
 |InplaceDimShuffle{x} [id B]
 | |x [id C]
 |Elemwise{exp,no_inplace} [id D]
   |y [id E]
```

This contains a lot of detail that is irrelevant for most users:
1. Elemwise{...}. Almost all operations are `Elemwise` because users don't build graphs with scalars. I suggest we just call `Add`. The "type" of addition can be guessed from the input types which are visible with `print_type=True`. This will be even more relevant after #306 where everything that is not an `Elemwise` will likely be a `Blockwise`. We can maybe add a kwarg to show the exact Op that is being used.
2. The inplace/no_inplace is seldom important for users. Again this information is visible via either `print_destroy_map` or `print_view_map`. Maybe we can have a `print_memory_map` that is equivalent to setting both of those to two.
3. DimShuffles are incredibly common and obscure because it's a term only used in PyTensor. I suggest we specialize the name for the following 4 cases:
  1. ExpandDims{dims}
  2. DropDims{dims}
  3. Transpose{dims}

The default dprint for the above graph would then look something like:
```
Add [id A]
 |ExpandDims{0} [id B]
 | |x [id C]
 |Exp [id D]
   |y [id E]
```

And `dprint(print_type=True, print_memory_map=True)`
```
Add [id A] <TensorType(float64, (?,))>
 |ExpandDims{0} [id B] <TensorType(float64, (1,))> v={0: [0]}
 | |x [id C] <TensorType(float64, ())>
 |Exp [id D] <TensorType(float64, (?,))>
   |y [id E] <TensorType(float64, (?,))>
```

Which I think is way more readable! We can go one step further and rename `<TensorType(float64, (?,))` to `<Tensor(float64, shape=(?,))` or ever `<TensorVector(float64, shape=(?,))`

### PR DESCRIPTION
**Pull request by ricardoV94**
**Please if you can: try with some examples of your own and give feedback** Specially if you have suggestions for Ops that have awful names that could be rendered better. I only tackled some I could think from memory.

Closes #313 
Closes #196 

Example from the issue:
```python
import pytensor
import pytensor.tensor as pt

x = pt.scalar("x")
y = pt.vector("y")
z = x + pt.exp(y)

pytensor.dprint(z)
```
Before:
```
Elemwise{add,no_inplace} [id A]
 |InplaceDimShuffle{x} [id B]
 | |x [id C]
 |Elemwise{exp,no_inplace} [id D]
   |y [id E]
```

After:
```
Add [id A]
 ├─ ExpandDims{axis=0} [id B]
 │  └─ x [id C]
 └─ Exp [id D]
    └─ y [id E]
```

Before with `print_type=True`
```
Elemwise{add,no_inplace} [id A] <TensorType(float64, (?,))>
 |InplaceDimShuffle{x} [id B] <TensorType(float64, (1,))>
 | |x [id C] <TensorType(float64, ())>
 |Elemwise{exp,no_inplace} [id D] <TensorType(float64, (?,))>
   |y [id E] <TensorType(float64, (?,))>
```

After with `print_type=True`
```
Add [id A] <Vector(float64, shape=(?,))>
 ├─ ExpandDims{axis=0} [id B] <Vector(float64, shape=(1,))>
 │  └─ x [id C] <Scalar(float64, shape=())>
 └─ Exp [id D] <Vector(float64, shape=(?,))>
    └─ y [id E] <Vector(float64, shape=(?,))>
```

A more crazy one:
```python
import pytensor
import pytensor.tensor as pt

x = pt.vector()
y = pt.matrix("y")
z = x + pt.exp(y)
out1 = pt.squeeze(z[None, None, None, None][:1, 0, None, 0, 1, 2])
out2 = z.T
out3 = z.dimshuffle((1, "x", 0)).sum((0, 1, 2))
outs = [out1, out2, out3]

pytensor.dprint(outs)
```
Before:
```
InplaceDimShuffle{2} [id A]
 |Subtensor{:int64:, int64, ::, int64, int64, int64} [id B]
   |InplaceDimShuffle{0,1,x,2,3,4,5} [id C]
   | |InplaceDimShuffle{x,x,x,x,0,1} [id D]
   |   |Elemwise{add,no_inplace} [id E]
   |     |InplaceDimShuffle{x,0} [id F]
   |     | |<TensorType(float64, (?,))> [id G]
   |     |Elemwise{exp,no_inplace} [id H]
   |       |y [id I]
   |ScalarConstant{1} [id J]
   |ScalarConstant{0} [id K]
   |ScalarConstant{0} [id L]
   |ScalarConstant{1} [id M]
   |ScalarConstant{2} [id N]
InplaceDimShuffle{1,0} [id O]
 |Elemwise{add,no_inplace} [id E]
Sum{axis=[0, 1, 2], acc_dtype=float64} [id P]
 |InplaceDimShuffle{1,x,0} [id Q]
   |Elemwise{add,no_inplace} [id E]
```
After:
```
DropDims{axes=[0, 1]} [id A]
 └─ Subtensor{:stop, i, :, j, k, ii} [id B]
    ├─ ExpandDims{axis=2} [id C]
    │  └─ ExpandDims{axes=[0, 1, 2, 3]} [id D]
    │     └─ Add [id E]
    │        ├─ ExpandDims{axis=0} [id F]
    │        │  └─ <Vector(float64, shape=(?,))> [id G]
    │        └─ Exp [id H]
    │           └─ y [id I]
    ├─ 1 [id J]
    ├─ 0 [id K]
    ├─ 0 [id L]
    ├─ 1 [id M]
    └─ 2 [id N]
Transpose{axes=[1, 0]} [id O]
 └─ Add [id E]
    └─ ···
Sum{axes=[0, 1, 2]} [id P]
 └─ DimShuffle{order=[1,x,0]} [id Q]
    └─ Add [id E]
       └─ ···
```

Something with inner graphs
```python
import pytensor
import pytensor.tensor as pt

x = pt.scalar("x")
y = pt.vector("y")
z = x + pt.exp(y)
w = z + 2

fn = pytensor.function([x, y], [z, w])
pytensor.dprint(fn)
```
Before:
```
Elemwise{Composite}.0 [id A] 1
 |y [id B]
 |InplaceDimShuffle{x} [id C] 0
 | |x [id D]
 |TensorConstant{(1,) of 2.0} [id E]
Elemwise{Composite}.1 [id A] 1

Inner graphs:

Elemwise{Composite}.0 [id A]
 >add [id F]
 > |<float64> [id G]
 > |exp [id H]
 >   |<float64> [id I]
 >add [id J]
 > |<float64> [id K]
 > |<float64> [id G]
 > |exp [id H]
Elemwise{Composite}.1 [id A]
 >add [id F]
 >add [id J]
```

After:
```
Composite{...}.0 [id A] 1
 ├─ y [id B]
 ├─ ExpandDims{axis=0} [id C] 0
 │  └─ x [id D]
 └─ [2.] [id E]
Composite{...}.1 [id A] 1
 └─ ···
Inner graphs:
Composite{...} [id A]
 ← add [id F] 'o0'
    ├─ i1 [id G]
    └─ exp [id H] 't0'
       └─ i0 [id I]
 ← add [id J] 'o1'
    ├─ i2 [id K]
    ├─ i1 [id G]
    └─ exp [id H] 't0'
       └─ ···
```

### CODE REVIEW

**Comment by ricardoV94** [comment]
Apparently someone decided to test rewrites from the dprint -.- ...

**Comment by ricardoV94** [comment]
Tests are passing, so ready for review

**Comment by twiecki** [comment]
Does it need to stay `ScalarConstant{1}` or can it just be `1`?

**Comment by ricardoV94** [comment]
> Does it need to stay `ScalarConstant{1}` or can it just be `1`?

Updated

**Comment by ricardoV94** [comment]
Ready for review again

**Review by michaelosthege — APPROVED** [review]
Much nicer than before!

**Pull request merged**
