### PR TITLE
Include sphinx-design in environment.yml

### PR DESCRIPTION
**Pull request by HangenYuu**
## Description

Update `environment.yml` with a new package `sphinx-design` so that doc can be built locally. Package is already added in `doc/environment.yml`.

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [x] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by HangenYuu** [comment]
Any packages added to `doc/environment.yml` must also be added to `environment.yml`

**Comment by twiecki** [comment]
Isn't the idea to install from `requirements-doc.txt` if you want to compile docs locally?

**Comment by OriolAbril** [comment]
I don't think there is any `requirements-docs.txt` here in pytensor. If there is, it is ignored and should be removed. [RTD uses the conda env inside `doc/`](https://github.com/pymc-devs/pytensor/blob/main/readthedocs.yml)

**Comment by HangenYuu** [comment]
> Isn't the idea to install from `requirements-doc.txt` if you want to compile docs locally?

There is no `requirements-doc.txt` anymore, we have switched to `doc/environment.yml` some time in the past. But the dependencies in this are already in `environment.yml` after #717. With this, developers can build docs locally with just one environment from `environment.yml`. `doc/environment.yml` is kept for the documentation building workflow.

**Review by twiecki — APPROVED** [review]

**Pull request merged**
