### PR TITLE
Handle implicit broadcasting correctly in RandomVariable vectorization

### LINKED ISSUE #650: Vectorization of RandomVariables failing
### Description

```python
from pytensor.graph.replace import vectorize_graph
import pytensor.tensor as pt

mu = pt.tensor("mu", shape=(5, 3))
sigma = pt.tensor("sigma", shape=())
x = pt.random.normal(mu, sigma)

new_x = vectorize_graph(
    x,
    replace={
        mu: pt.tensor("mu", shape=(10, 5, 3)),
        sigma: pt.tensor("sigma", shape=(10,)),
    }
)
```
```python
ValueError: Could not broadcast dimensions. Incompatible shapes were [(ScalarConstant(ScalarType(int64), data=10), ScalarConstant(ScalarType(int64), data=5), ScalarConstant(ScalarType(int64), data=3)), (ScalarConstant(ScalarType(int64), data=1), ScalarConstant(ScalarType(int64), data=1), ScalarConstant(ScalarType(int64), data=10))].
```

With size we get another error
```python
x = pt.random.normal(mu, sigma, size=mu.shape)
new_x = vectorize_graph(
    x,
    replace={
        mu: pt.tensor("mu", shape=(10, 5, 3)),
        sigma: pt.tensor("sigma", shape=(10,)),
    }
)
```
```python
ValueError: Tensor of type Matrix(int64, shape=(10, 2)) could not be cast to have 1 dimensions
```

### PR DESCRIPTION
**Pull request by ricardoV94**
## Related Issue

- [x] Closes #650 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [x] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

### CODE REVIEW

**Comment by jessegrabowski** [comment]
What an example of a graph that is currently incorrectly vectorized?

**Comment by ricardoV94** [comment]
> What's an example of a graph that is currently incorrectly vectorized?

MWE in original issue and all new tests

**Comment by ricardoV94** [comment]
Tests are passing

**Review by jessegrabowski — APPROVED** [review]
LGTM

**Pull request merged**
