### PR TITLE
Add aliases for arithmetic inequality function equivalents in NumPy

### PR DESCRIPTION
**Pull request by lmmx**
### Motivation for these changes

Updated the logical function mappings in PyTensor to align with NumPy's logical functions. This enhances compatibility and eases the transition for users familiar with NumPy, making PyTensor more intuitive and accessible.

Fulfils:

- #462

### Implementation details

I reviewed the correspondence and made a table [in the issue tracker](https://github.com/pymc-devs/pytensor/issues/462#issuecomment-1843511101), then made aliases for those that were not a direct name match. I also added them to the `__all__` alongside the names they alias.

### Checklist

+ [x] Explain motivation and implementation 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None, compatibility was added not removed

## New features
- New aliases for tensor logic functions

## Bugfixes
- N/A

## Documentation
- Documented in the style of the existing NumPy aliases

## Maintenance
- N/A

### CODE REVIEW

**Comment by jessegrabowski** [comment]
I think it would be great to gather everything into one place

**Review by ricardoV94 — APPROVED** [review]

**Comment by ricardoV94** [comment]
Need to fix conflicts with changes in main, otherwise ready to merge

**Comment by lmmx** [comment]
On my 3rd try at interactive rebasing I gave up and did it in the web editor! :face_exhaling: It kept saying there were going to be 26 commits, I briefly saw the option to squash but it didn't show up on 2nd try, think that was the right way.

Oh well, should be good now, looks like the web editor didn't mess up the code style check

**Comment by ricardoV94** [comment]
Thanks @lmmx and sorry for the for pain!

**Pull request merged**
