### PR TITLE
Use empty blas_ldflags if no cxx is configured

### LINKED ISSUE #504: blas IndexError: list index out of range error
### Description

```
~ $ python -c "import pytensor"
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/configparser.py", line 202, in fetch_val_for_key
    return self._pytensor_cfg.get(section, option)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'blas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/configparser.py", line 318, in __get__
    val_str = cls.fetch_val_for_key(self.name, delete_key=delete_key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/configparser.py", line 206, in fetch_val_for_key
    raise KeyError(key)
KeyError: 'blas__ldflags'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/__init__.py", line 119, in <module>
    from pytensor import scalar, tensor
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/tensor/__init__.py", line 107, in <module>
    from pytensor.tensor import (  # noqa
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/tensor/blas.py", line 101, in <module>
    from pytensor.tensor.blas_headers import blas_header_text, blas_header_version
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/tensor/blas_headers.py", line 1015, in <module>
    if not config.blas__ldflags:
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/configparser.py", line 322, in __get__
    val_str = self.default()
              ^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/link/c/cmodule.py", line 2782, in default_blas_ldflags
    cxx_library_dirs = get_cxx_library_dirs()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/pytensor/link/c/cmodule.py", line 2734, in get_cxx_library_dirs
    maybe_lib_dirs = [
                     ^
IndexError: list index out of range
```

Could be related to https://github.com/pymc-devs/pytensor/pull/444 ? CC @lucianopaz

### PR DESCRIPTION
**Pull request by lucianopaz**
Closes #504 

## Major / Breaking Changes
- ...

## New features
- ...

## Bugfixes
- Default blas_ldflags are empty if no compiler is configured

## Documentation
- ...

## Maintenance
- ...

### CODE REVIEW

**Comment by ricardoV94** [comment]
@lucianopaz do you think it's worth it to add a test?

**Comment by lucianopaz** [comment]
In all honesty, I don’t know how to test this properly. I know that I can mock the cxx config but I’m not sure if that we’ll have us completely covered. @twiecki, could you try out this branch when there is no compiler and see if it works?

**Comment by ricardoV94** [comment]
> In all honesty, I don’t know how to test this properly. I know that I can mock the cxx config but I’m not sure if that we’ll have us completely covered. @twiecki, could you try out this branch when there is no compiler and see if it works?

Why mock? Can't you use the context manager `with pytensor.config.change_flags(cxx="")`.

**Comment by lucianopaz** [comment]
> > In all honesty, I don’t know how to test this properly. I know that I can mock the cxx config but I’m not sure if that we’ll have us completely covered. @twiecki, could you try out this branch when there is no compiler and see if it works?
> 
> Why mock? Can't you use the context manager `with pytensor.config.change_flags(cxx=""): ...`.
> 
> Edit: Or this fails more internally? If so, ignore me

Yes you're right, I can use the context manager instead. I realized now that I didn't cover the potential for failures in [this part of the code](https://github.com/pymc-devs/pytensor/pull/506/files#diff-66c7250f6c90a093b93652c2b62cd0edd0473c1bd0b891bc9613bd9242050fecR2725-L2733). If `cxx  -print-search-dirs` fails to run for whatever reason, it can mean many things:

1. The `cxx` command isn't in the path and we wont be able to compile C extensions
2. The `cxx` command doesn't have a print-search-dirs argument (gcc and clang do have it, but I don't know if this is a standard C compiler thing)
3. Something deeper went wrong and we wont be able to compile.

I think that I'll add some guardrails for that case in this PR and write a test for it too.

**Comment by lucianopaz** [comment]
@ricardoV94, @twiecki, can I bother you to try out this PR and see if it breaks your installations that used:
- No c compiler
- Blas on Linux
- Accelerate on Mac
- MKL on Intel

**Comment by ricardoV94** [comment]
Mine doesn't seem to have changed:

## Main:
```bash
python -c "import pytensor; print(pytensor.config.blas__ldflags)"
-L/home/ricardo/miniconda3/envs/pytensor/lib -llapack -lblas -lcblas -lm -Wl,-rpath,/home/ricardo/miniconda3/envs/pytensor/lib
```
```bash
PYTENSOR_FLAGS='cxx=""' python -c "import pytensor; print(pytensor.config.blas__ldflags)"
# IndexError: list index out of range
```

## PR:
```bash
python -c "import pytensor; print(pytensor.config.blas__ldflags)"
-L/home/ricardo/miniconda3/envs/pytensor/lib -llapack -lblas -lcblas -lm -Wl,-rpath,/home/ricardo/miniconda3/envs/pytensor/lib
```
```bash
PYTENSOR_FLAGS='cxx=""' python -c "import pytensor; print(pytensor.config.blas__ldflags)"
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

**Pull request merged**
