### PR TITLE
Is in ancestor caching

### PR DESCRIPTION
**Pull request by ferrine**
Implemented a refactored version of the util to make the complete split for the graph

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [x] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.
+ [x] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by ricardoV94** [comment]
Can we add it as a separate function?

**Comment by ferrine** [comment]
> Can we add it as a separate function?

Hmm, this will duplicate the functionality, isn't it?

**Comment by ricardoV94** [comment]
> > Can we add it as a separate function?
> 
> Hmm, this will duplicate the functionality, doesn't it?

It makes reviewing easier. Otherwise can you provide more context to motivate these changes? Why is this needed? There's no issue associated with it.

**Comment by ferrine** [comment]
> > > Can we add it as a separate function?
> > 
> > 
> > Hmm, this will duplicate the functionality, doesn't it?
> 
> It makes reviewing easier, as we don't need to worry about back-compatibility.
> 
> Otherwise can you provide more context to motivate these changes? Why is this needed? There's no issue associated with it.

If you traverse the graph and query if an apply depends on other apply and do that frequently, known_(in)dependent cut the query costs

**Comment by ricardoV94** [comment]
Can you clarify where this was a bottleneck that warrants the extra complexity?

**Comment by ferrine** [comment]
> Can you clarify where this was a bottleneck that warrants the extra complexity?

Adding the fuctionality `pytensor.graph.replace` (https://github.com/pymc-devs/pytensor/issues/19) I am not sure I can write clean code avoiding multiple is_ancestor calls. However, I still believe there might be a solution to figure it out from toposort and extra containers.

**Comment by ferrine** [comment]
Here is the candidate implementation for the #19 https://github.com/pymc-devs/pytensor/blob/graph-replace/pytensor/graph/basic.py#L1924, I use the updated version of the is_in_ancestor and it helps there, the thing especially needed is multiple inputs for the f_apply arg

**Pull request closed without merging**
